title: "Ashok Raj Vijayakumar — Portfolio"
description: "SEO case studies, audits, and automation."
baseurl: "/seo-portfolio"   # ← important for project sites
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
